/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
	sidebar: [
		{
			type: "category",
			label: "Introduction",
			collapsed: false,
			items: ["introduction/introduction", "introduction/workflow"],
		},
		{
			type: "category",
			label: "Managing dependencies",
			collapsed: false,
			items: [
				"dependencies/introduction",
				"dependencies/npm",
				"dependencies/client",
				"dependencies/client_login",
				"dependencies/client_import_maps",
				"dependencies/client_putting_it_all_together",
				"dependencies/mapping_import_map",
				"dependencies/mapping_browser",
				"dependencies/mapping_plugins",
			],
		},
		{
			type: "category",
			label: "Eik server",
			items: [
				"server/server",
				"server/js-api",
				"server/sink",
				"server/http-api",
				"server/file-structure",
				"server/metrics",
			],
		},
		{
			type: "category",
			label: "Guides",
			items: ["guides/travis"],
		},
		{
			type: "category",
			label: "Reference",
			items: [
				{
					type: "autogenerated",
					dirName: "reference",
				},
			],
		},
	],
};
